---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml

default:
  image: ${BASE_CONTAINER_REGISTRY}/python3.7-builder:${BASE_CONTAINER_VERSION}
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  tags:
    - dind

variables:
  PG_INDEXD_HOST: postgres

.prepareTox:
  script:
    - !reference [.load_github_key, script]
    - apt-get update && apt-get install -y gnupg
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main 13" | tee /etc/apt/sources.list.d/pgdg.list
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7FCC7D46ACCC4CF8
    - apt-get update
    - apt-get install -y postgresql-client-13
    - rm /usr/bin/pg_config
    - ln /usr/lib/postgresql/13/bin/pg_config /usr/bin/
    - pip install "tox<4"

tox:
  stage: test
  variables:
    USE_PYTEST_INDEXD: 'false'
    USE_RUNNING_PG: 'true'
  before_script:
    - !reference [.prepareTox, script]
  script:
    - tox

test utils2 proc:
  stage: test
  variables:
    USE_PYTEST_INDEXD: 'true'
    USE_RUNNING_PG: 'false'
  before_script:
    - !reference [.prepareTox, script]
  script:
    - tox

test utils2 noproc:
  stage: test
  variables:
    USE_PYTEST_INDEXD: 'true'
  before_script:
    - !reference [.prepareTox, script]
  script:
    - tox

tox parallel:
  stage: test
  before_script:
    - !reference [.prepareTox, script]
  script:
    - tox -e parallel

xdist:
  stage: test
  before_script:
    - !reference [.prepareTox, script]
  script:
    - tox -e xdist
