---
variables:
  LANGUAGE_VERSION: python3.9

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.8.0
    file:
      - templates/artifacts/python-library.yaml

tox:
  parallel:
    matrix:
      - LANGUAGE_VERSION:
          - python3.7
          - python3.8
          - python3.9
          - python3.10
          - python3.11
        TOX_ENV:
          - fixtures
          - plugin
          - test
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  variables:
    PG_INDEXD_HOST: postgres
    PG_INDEXD_ROOT_USER: test
    PG_INDEXD_ROOT_PASS: test
    POSTGRES_DB: indexd_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
  before_script:
    - pip install tox
  script:
    - tox -e ${TOX_ENV}-${LANGUAGE_VERSION}
