os: linux
dist: bionic
language: python

sudo: false

addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
      - pipx

before_install:
  # Copy custom configs from the repo because PG-13 isn't set up to run like
  # it normally does on Travis out of the box.
  - sudo cp travis/postgresql.conf /etc/postgresql/13/main/postgresql.conf
  - sudo cp travis/pg_hba.conf /etc/postgresql/13/main/pg_hba.conf
  - sudo pg_ctlcluster 13 main restart

install:
  - pipx install poetry
  - pipx inject poetry poetry-dynamic-versioning
  - pip install tox-travis tox-poetry

prerelease_install: &prerelease_install
  # For py37 and py38 setuptools 62.X.X is causing failures in creating virtual
  # environments. This has been solved in the latest pre-release and this should
  # be a temporary measure until the 63.X.X is officially released.
  install:
    - pip install setuptools --pre --force-reinstall
    - pip install poetry tox-travis tox-poetry poetry-dynamic-versioning

script:
  - tox

jobs:
  allow_failures:
    - python: "3.11-dev"
  include:
    - python: "3.7"
    # - python: "3.8"
    #   <<: *prerelease_install
    # - python: "3.6"
    # - python: "3.9"
    # - python: "3.10"
    # - python: "3.11-dev"
