[build-system]
requires = ["setuptools<81.0.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
  "coverage[toml]",
  "indexd",
  "pytest>=6",
  "pytest-cov",
  "setuptools<81.0.0",
  "sqlalchemy",
  "sqlalchemy-utils"
]

[project]
name = "indexclient"
description = "IndexD python API client"
readme = "README.md"
authors = [{name = "GDC Feature Team", email = "gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com"}]
maintainers = [{name = "GDC Feature Team", email = "gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com"}]
license-files = ["LICENSE"]
keywords = ["Genomic Data Commons", "IndexD", "REST", "indexclient"]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11"
]
requires-python = ">=3.7"
dependencies = ["requests"]
dynamic = [
  "version"
]

[project.optional-dependencies]
pytest_indexd = [
  "deepdiff",
  "importlib-resources",
  "psycopg",
  "pytest",
  "pytest-cov[toml]",
  "pytest-postgresql",
  "pytest-xdist",
  "pyyaml",
  "indexd",
  "indexdmodels",
  "setuptools<81.0.0"
]

[project.urls]
Repository = "https://github.com/NCI-GDC/indexclient"

[tool.black]
include = '\.pyi?$'
line-length = 98

[tool.coverage.html]
title = "indexclient coverage report"
directory = "docs/htmlcov"
show_contexts = true

[tool.coverage.run]
branch = true
context = "unit tests"
source = ["indexclient"]

[tool.isort]
profile = "black"
known_first_party = ["indexclient"]

[tool.pytest.ini_options]
minversion = 6.0
# Silence warning by opting in to use pytest 6's new default value
junit_family = "xunit2"
junit_logging = "system-out"
console_output_style = "classic"
log_cli_level = "INFO"
log_cli = "true"
addopts = "-rfE --color=yes --maxfail=10 --cov=indexclient --cov-report term"
norecursedirs = [
  ".git",
  ".tox",
  "dist",
  "build"
]
testpaths = [
  "tests/unit"
]

[tool.setuptools_scm]
fallback_version = "0.0.0"
