[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "indexclient"
dynamic = ["version"]
dependencies = [
  "requests~=2.5"
]
requires-python = ">= 3.7"
authors = [
  {name = "Gdc feature team", email = "gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com"}
]
description = "data indexing and tracking client"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["indexclient", "indexd"]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9"
]

[project.optional-dependencies]
dev = [
  "markupsafe", # newer version not compatible
  "pytest",
  "pytest-cov[toml]",
  "sqlalchemy~=1.3.0",
  "sqlalchemy-utils>=0.32,<0.36.4",
  "indexd"
]
pytest_indexd = [
  "deepdiff",
  "importlib_resources",
  "psycopg",
  "pytest",
  "pytest-cov[toml]",
  "pytest-postgresql",
  "pytest-xdist",
  "pyyaml",
  "indexd",
  "indexdmodels"
]

[project.urls]
Homepage = "https://github.com/NCI-GDC/indexclient"

[tool.black]
line-length = 98
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 98
known_first_party = ["indexclient", "indexd_test_utils", "pytest_indexd"]

[tool.setuptools.packages.find]
where = ["src/"]
include = ["indexclient", "indexd_test_utils", "pytest_indexd"]

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "src/indexclient/_version.py"
