[tox]
envlist= py37

[testenv]
passenv =
    USE_TEST_UTILS2

deps=
    -rdev-requirements.txt

install_command = python -m pip install --no-deps {opts} {packages}

commands=
    env
    pip install . --force --upgrade
    python -m pytest {posargs: -lvvvs tests}

[testenv:parallel]
setenv =
    USE_TEST_UTILS2 = true
;    mac
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY = YES

deps=
    -rdev-requirements.txt

install_command = python -m pip install --no-deps {opts} {packages}

commands=
    env
    pip install . --force --upgrade
    python -m pytest {posargs: -lvvvs tests} --workers auto

[testenv:xdist]
setenv =
    USE_TEST_UTILS2 = true
;    mac
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY = YES

deps=
    -rdev-requirements.txt

install_command = python -m pip install --no-deps {opts} {packages}

commands=
    env
    pip install . --force --upgrade
    python -m pytest {posargs: -lvvvs tests} -n 2
