[tox]
envlist= py37

[testenv]
passenv =
    PG_INDEXD_HOST
setenv =
    NO_PROXY=localhost,postgres
    no_proxy=localhost,postgres
    USE_PYTEST_INDEXD=true
deps=
    -rdev-requirements.txt
install_command = python -m pip install --no-deps {opts} {packages}
commands=
    env
    python -m pytest

[testenv:fixtures]
basepython = python3.6
passenv =
    PG_*
setenv =
    NO_PROXY=localhost,postgres
    no_proxy=localhost,postgres
    USE_PYTEST_INDEXD=false
deps=
    -rdev-requirements.txt

install_command = python -m pip install --no-deps {opts} {packages}
commands=
    env
    python -m pytest {posargs: -lvvvs tests/integration/test_client.py}



[testenv:plugin]
basepython = python3.6
passenv =
    PG_*
    USE_*
setenv =
    USE_RUNNING_PG=false
    USE_PYTEST_INDEXD=true
    NO_PROXY=localhost,postgres
    no_proxy=localhost,postgres
;    MacOS requires the following environment variable to run test in parallel
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY = YES

deps=
    -rpytest-indexd-requirements.txt

install_command = python -m pip install --no-deps {opts} {packages}

commands=
    env
    # Limit the number of processes to avoid postgres too many clients already
    python -m pytest {posargs: -lvvvs tests/integration} -n auto --maxprocesses=8

[testenv:lint]
basepython = python3.8
skip_install = True
commands_pre =
deps =
    pre-commit
commands =
    pre-commit run --all-files --show-diff-on-failure {posargs: }
