[tox]
envlist= py37

[testenv]
passenv =
    USE_PYTEST_INDEXD
    USE_RUNNING_PG
    PG_INDEXD_HOST

setenv =
    NO_PROXY=localhost,postgres
    no_proxy=localhost,postgres

deps=
    -rdev-requirements.txt

install_command = python -m pip install --no-deps {opts} {packages}

commands=
    env
    pip install . --force --upgrade
    python -m pytest {posargs: -lvvvs tests}

[testenv:parallel]
setenv =
    USE_PYTEST_INDEXD = true
    USE_RUNNING_PG = false
;    MacOS requires the following environment variable to run test in parallel
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY = YES

deps=
    -rdev-requirements.txt

install_command = python -m pip install --no-deps {opts} {packages}

commands=
    env
    pip install . --force --upgrade
    python -m pytest {posargs: -lvvvs tests} --workers auto

[testenv:xdist]
passenv =
    USE_RUNNING_PG
setenv =
    USE_PYTEST_INDEXD = true
;    MacOS requires the following environment variable to run test in parallel
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY = YES

deps=
    -rdev-requirements.txt

install_command = python -m pip install --no-deps {opts} {packages}

commands=
    env
    pip install . --force --upgrade
    python -m pytest {posargs: -lvvvs tests} -n auto
